[package]
name = "aoscdk-rs"
version = "0.2.1-alpha.0"
authors = ["liushuyu <liushuyu011@gmail.com>"]
edition = "2018"


[dependencies]
nom = "^7"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0"
anyhow = "1.0"
reqwest = { version = "0.11", features = ["json", "blocking"] }
nix = "0.23"
libparted = "0.1"
cursive = "0.16"
cursive_table_view = { git = "https://github.com/BonsaiDen/cursive_table_view" }
lazy_static = "1.4"
number_prefix = "0.4"
xz2 = "0.1"
tar = "0.4"
sha2 = "0.10"
hex = "0.4"
tempfile = "3.2"
cursive-async-view = "0.5"
tokio = { version = "1.15", features = ["rt", "rt-multi-thread"]}
futures = "0.3"
rand = "0.8"

[features]
is_retro = []

[profile.release]
lto = true
